/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sbml.libsbml;

public class MathML {
   private long swigCPtr;
   protected boolean swigCMemOwn;

   protected MathML(long cPtr, boolean cMemoryOwn)
   {
     swigCMemOwn = cMemoryOwn;
     swigCPtr    = cPtr;
   }

   protected static long getCPtr(MathML obj)
   {
     return (obj == null) ? 0 : obj.swigCPtr;
   }

   protected static long getCPtrAndDisown (MathML obj)
   {
     long ptr = 0;

     if (obj != null)
     {
       ptr             = obj.swigCPtr;
       obj.swigCMemOwn = false;
     }

     return ptr;
   }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsbmlJNI.delete_MathML(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  
/** * @internal */ public
 MathML(SBMLNamespaces sbmlns) {
    this(libsbmlJNI.new_MathML__SWIG_0(SBMLNamespaces.getCPtr(sbmlns), sbmlns), true);
  }

  
/** * @internal */ public
 MathML() {
    this(libsbmlJNI.new_MathML__SWIG_1(), true);
  }

  
/** * @internal */ public
 void setPrefix(String prefix) {
    libsbmlJNI.MathML_setPrefix(swigCPtr, this, prefix);
  }

}
