// This file is autogenerated and will be overwritten by the configuration process

%include "arrays-package.i"
%include "comp-package.i"
%include "distrib-package.i"
%include "fbc-package.i"
%include "groups-package.i"
%include "layout-package.i"
%include "qual-package.i"
%include "render-package.i"
%include "req-package.i"
%include "spatial-package.i"

