// This file is autogenerated and will be overwritten by the configuration process

%include "local-downcast-namespaces-arrays.i"
%include "local-downcast-namespaces-comp.i"
%include "local-downcast-namespaces-distrib.i"
%include "local-downcast-namespaces-fbc.i"
%include "local-downcast-namespaces-groups.i"
%include "local-downcast-namespaces-layout.i"
%include "local-downcast-namespaces-qual.i"
%include "local-downcast-namespaces-render.i"
%include "local-downcast-namespaces-req.i"
%include "local-downcast-namespaces-spatial.i"

