// This file is autogenerated and will be overwritten by the configuration process

%include "local-packages-arrays.i"
%include "local-packages-comp.i"
%include "local-packages-distrib.i"
%include "local-packages-fbc.i"
%include "local-packages-groups.i"
%include "local-packages-layout.i"
%include "local-packages-qual.i"
%include "local-packages-render.i"
%include "local-packages-req.i"
%include "local-packages-spatial.i"

