// This file is autogenerated and will be overwritten by the configuration process

%include "local-downcast-namespaces-comp.i"
%include "local-downcast-namespaces-fbc.i"
%include "local-downcast-namespaces-layout.i"
%include "local-downcast-namespaces-qual.i"

