// This file is autogenerated and will be overwritten by the configuration process

%include "local-downcast-extension-comp.i"
%include "local-downcast-extension-fbc.i"
%include "local-downcast-extension-layout.i"
%include "local-downcast-extension-qual.i"

