// This file is autogenerated and will be overwritten by the configuration process

%include "local-downcast-extension-comp.i"
%include "local-downcast-extension-fbc.i"
%include "local-downcast-extension-groups.i"
%include "local-downcast-extension-layout.i"
%include "local-downcast-extension-qual.i"
%include "local-downcast-extension-render.i"
%include "local-downcast-extension-req.i"
%include "local-downcast-extension-spatial.i"

