/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace libsbml {

using System;
using System.Runtime.InteropServices;

public class MathML : IDisposable {
	private HandleRef swigCPtr;
	protected bool swigCMemOwn;
	
	internal MathML(IntPtr cPtr, bool cMemoryOwn)
	{
		swigCMemOwn = cMemoryOwn;
		swigCPtr    = new HandleRef(this, cPtr);
	}
	
	internal static HandleRef getCPtr(MathML obj)
	{
		return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
	}
	
	internal static HandleRef getCPtrAndDisown (MathML obj)
	{
		HandleRef ptr = new HandleRef(null, IntPtr.Zero);
		
		if (obj != null)
		{
			ptr             = obj.swigCPtr;
			obj.swigCMemOwn = false;
		}
		
		return ptr;
	}

  ~MathML() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          libsbmlPINVOKE.delete_MathML(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  
/** */ /* libsbml-internal */ public
 MathML(SBMLNamespaces sbmlns) : this(libsbmlPINVOKE.new_MathML__SWIG_0(SBMLNamespaces.getCPtr(sbmlns)), true) {
  }

  
/** */ /* libsbml-internal */ public
 MathML() : this(libsbmlPINVOKE.new_MathML__SWIG_1(), true) {
  }

  
/** */ /* libsbml-internal */ public
 void setPrefix(string prefix) {
    libsbmlPINVOKE.MathML_setPrefix(swigCPtr, prefix);
  }

}

}
