/* This file is autogenerated and will be overwritten by the configuration process */

%include "local-comp.i"
%include "local-contrib.i"
%include "local-doc-extras.i"
%include "local-fbc.i"
%include "local-layout.i"
%include "local-qual.i"

