# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target f2c
ADD_LIBRARY(f2c STATIC IMPORTED)

# Create imported target blas
ADD_LIBRARY(blas STATIC IMPORTED)

# Create imported target lapack
ADD_LIBRARY(lapack STATIC IMPORTED)

# Import target "f2c" for configuration "Release"
SET_PROPERTY(TARGET f2c APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(f2c PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "D:/Development/clapack-3.2.1/F2CLIBS/libf2c/libf2c.lib"
  )

# Import target "blas" for configuration "Release"
SET_PROPERTY(TARGET blas APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(blas PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "f2c"
  IMPORTED_LOCATION_RELEASE "D:/Development/clapack-3.2.1/BLAS/SRC/blas.lib"
  )

# Import target "lapack" for configuration "Release"
SET_PROPERTY(TARGET lapack APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(lapack PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "blas"
  IMPORTED_LOCATION_RELEASE "D:/Development/clapack-3.2.1/SRC/lapack.lib"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
