/* src/common/libnuml-package.h.  Generated from libnuml-package.h.in by configure.  */
/**
* Begin svn Header
* $Rev: 27 $:	Revision of last commit
* $Author: josephodada@gmail.com $:	Author of last commit
* $Date: 2013-04-25 10:07:15 +0100 (Thu, 25 Apr 2013) $:	Date of last commit
* $HeadURL: https://numl.googlecode.com/svn/trunk/libnuml/src/common/libnuml-package.h.in $
* $Id: libnuml-package.h.in 27 2013-04-25 09:07:15Z josephodada@gmail.com $
* End svn Header
* ***************************************************************************
* This file is part of libNUML.  Please visit http://code.google.com/p/numl/for more
* information about NUML, and the latest version of libNUML.
* Copyright (c) 2013 The University of Manchester.
*
* This library is free software; you can redistribute it and/or modify it
* under the terms of the GNU Lesser General Public License as published
* by the Free Software Foundation.  A copy of the license agreement is
* provided in the file named "LICENSE.txt" included with this software
* distribution and also available online as http://www.gnu.org/licenses/lgpl.html
*
* The original code was initially developed by:
*
* 	SBML Team
* 	Control and Dynamical Systems, MC 107-81
* 	California Institute of Technology
* 	Pasadena, CA, 91125, USA
*
*  	http://www.sbml.org
* 	mailto:sbml-team@caltech.edu
*
* Adapted for NUML by:
*
* 	NUML Team
* 	Computational Systems Biology Group
* 	School of Computer Science
* 	The University of Manchester
* 	Manchester, M1 7DN UK
* 	mailto:josephodada@gmail.com
*
*   Contributor(s):
*   Joseph O. Dada, The University of Manchester - initial LIBNUML API and implementation
* ***************************************************************************
**/

/**
 *
 * The file <tt>libnuml-package.h</tt> is generated from the file
 * <tt>libnuml-package.h.in</tt> by the @c configure script at the top
 * level of the libNUML source tree.
 *
 * @note This file is handled unusually.  The file itself is generated by
 * @c configure, but unlike other files that are likewise automatically
 * generated, it is also checked into the source repository.  The need for
 * this is due to the fact that under Windows, developers may not be
 * running @c configure at all (e.g., if they are using the MSVC
 * environment).  The .h file therefore needs to be provided directly in
 * order for people to be able to compile the sources under Windows.
 * Developers must remember to check in the .h version of this file in the
 * source code repository prior to major releases, so that an up-to-date .h
 * file is present in distributions.  This is admittedly an undesirable and
 * error-prone situation, but it is currently the best alternative we have
 * been able to find.
 */


/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "dada@ieee.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libNUML"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libNUML @LIBNUML_VERSION@"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libnuml"

/* Define to the version of this package. */
#define PACKAGE_VERSION "@LIBNUML_VERSION@"
