// This file is autogenerated and will be overwritten by the configuration process

%include "local-packages-comp.i"
%include "local-packages-fbc.i"
%include "local-packages-layout.i"
%include "local-packages-qual.i"

