.TH "deprecated" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
 
.IP "\fBMember \fBQwtPlot::clear\fP() \fP" 1c
Use QwtPlotDeict::detachItems instead 
.PP
.PP
 
.IP "\fBClass \fBQwtPlotPrintFilter\fP \fP" 1c
In Qwt 5.0 the design of \fBQwtPlot\fP allows/recommends writing individual QwtPlotItems, that are not known to \fBQwtPlotPrintFilter\fP. So this concept is outdated and \fBQwtPlotPrintFilter\fP will be removed/replaced in Qwt 6.x. 
.PP

