.TH "QwtCompassMagnetNeedle" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtCompassMagnetNeedle \- A magnet needle for compass widgets.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_dial_needle.h>\fP
.PP
Inherits \fBQwtDialNeedle\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBStyle\fP { \fBTriangleStyle\fP, \fBThinStyle\fP }"
.br
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtCompassMagnetNeedle\fP (\fBStyle\fP=TriangleStyle, const QColor &light=Qt::white, const QColor &dark=Qt::red)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *, const QPoint &, int length, double direction, QPalette::ColorGroup=QPalette::Active) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdrawTriangleNeedle\fP (QPainter *, const QPalette &, QPalette::ColorGroup, const QPoint &, int length, double direction)"
.br
.ti -1c
.RI "static void \fBdrawThinNeedle\fP (QPainter *, const QPalette &, QPalette::ColorGroup, const QPoint &, int length, double direction)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdrawPointer\fP (QPainter *painter, const QBrush &brush, int colorOffset, const QPoint &center, int length, int width, double direction)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A magnet needle for compass widgets. 

A magnet needle points to two opposite directions indicating north and south.
.PP
The following colors are used:
.IP "\(bu" 2
QColorGroup::Light
.br
 Used for pointing south
.IP "\(bu" 2
QColorGroup::Dark
.br
 Used for pointing north
.IP "\(bu" 2
QColorGroup::Base
.br
 Knob (ThinStyle only)
.PP
.PP
\fBSee also:\fP
.RS 4
\fBQwtDial\fP, \fBQwtCompass\fP 
.RE
.PP

.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBQwtCompassMagnetNeedle::Style\fP"
.PP
Style of the needle. 
.PP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtCompassMagnetNeedle::QwtCompassMagnetNeedle (\fBStyle\fP style = \fCTriangleStyle\fP, const QColor & light = \fCQt::white\fP, const QColor & dark = \fCQt::red\fP)"
.PP
Constructor. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void QwtCompassMagnetNeedle::draw (QPainter * painter, const QPoint & center, int length, double direction, QPalette::ColorGroup colorGroup = \fCQPalette::Active\fP) const\fC [virtual]\fP"
.PP
Draw the needle
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIcenter\fP Center of the dial, start position for the needle 
.br
\fIlength\fP Length of the needle 
.br
\fIdirection\fP Direction of the needle, in degrees counter clockwise 
.br
\fIcolorGroup\fP Color group, used for painting 
.RE
.PP

.PP
Implements \fBQwtDialNeedle\fP.
.SS "void QwtCompassMagnetNeedle::drawPointer (QPainter * painter, const QBrush & brush, int colorOffset, const QPoint & center, int length, int width, double direction)\fC [static, protected]\fP"
.PP
Draw a compass needle
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIbrush\fP Brush 
.br
\fIcolorOffset\fP Color offset 
.br
\fIcenter\fP Center, where the needle starts 
.br
\fIlength\fP Length of the needle 
.br
\fIwidth\fP Width of the needle 
.br
\fIdirection\fP Direction 
.RE
.PP

.SS "void QwtCompassMagnetNeedle::drawThinNeedle (QPainter * painter, const QPalette & palette, QPalette::ColorGroup colorGroup, const QPoint & center, int length, double direction)\fC [static]\fP"
.PP
Draw a compass needle
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIpalette\fP Palette 
.br
\fIcolorGroup\fP Color group 
.br
\fIcenter\fP Center, where the needle starts 
.br
\fIlength\fP Length of the needle 
.br
\fIdirection\fP Direction 
.RE
.PP

.SS "void QwtCompassMagnetNeedle::drawTriangleNeedle (QPainter * painter, const QPalette & palette, QPalette::ColorGroup colorGroup, const QPoint & center, int length, double direction)\fC [static]\fP"
.PP
Draw a compass needle
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIpalette\fP Palette 
.br
\fIcolorGroup\fP Color group 
.br
\fIcenter\fP Center, where the needle starts 
.br
\fIlength\fP Length of the needle 
.br
\fIdirection\fP Direction 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
