.TH "QwtEventPattern::KeyPattern" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtEventPattern::KeyPattern \- A pattern for key events.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_event_pattern.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyPattern\fP (int k=0, int st=Qt::NoButton)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkey\fP"
.br
.ti -1c
.RI "int \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A pattern for key events. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
