.TH "QwtLog10ScaleEngine" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtLog10ScaleEngine \- A scale engine for logarithmic (base 10) scales.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_scale_engine.h>\fP
.PP
Inherits \fBQwtScaleEngine\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBautoScale\fP (int maxSteps, double &x1, double &x2, double &stepSize) const "
.br
.ti -1c
.RI "virtual \fBQwtScaleDiv\fP \fBdivideScale\fP (double x1, double x2, int numMajorSteps, int numMinorSteps, double stepSize=0.0) const "
.br
.ti -1c
.RI "virtual \fBQwtScaleTransformation\fP * \fBtransformation\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtDoubleInterval\fP \fBlog10\fP (const \fBQwtDoubleInterval\fP &) const "
.br
.ti -1c
.RI "\fBQwtDoubleInterval\fP \fBpow10\fP (const \fBQwtDoubleInterval\fP &) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
A scale engine for logarithmic (base 10) scales. 

The step size is measured in *decades* and the major step size will be adjusted to fit the pattern $\left\{ 1,2,3,5\right\} \cdot 10^{n}$, where n is a natural number including zero.
.PP
\fBWarning:\fP
.RS 4
the step size as well as the margins are measured in *decades*. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void QwtLog10ScaleEngine::autoScale (int maxNumSteps, double & x1, double & x2, double & stepSize) const\fC [virtual]\fP"
.PP
Align and divide an interval
.PP
\fBParameters:\fP
.RS 4
\fImaxNumSteps\fP Max. number of steps 
.br
\fIx1\fP First limit of the interval (In/Out) 
.br
\fIx2\fP Second limit of the interval (In/Out) 
.br
\fIstepSize\fP Step size (Out)
.RE
.PP
\fBSee also:\fP
.RS 4
\fBQwtScaleEngine::setAttribute()\fP 
.RE
.PP

.PP
Implements \fBQwtScaleEngine\fP.
.SS "\fBQwtScaleDiv\fP QwtLog10ScaleEngine::divideScale (double x1, double x2, int maxMajSteps, int maxMinSteps, double stepSize = \fC0.0\fP) const\fC [virtual]\fP"
.PP
Calculate a scale division. 
.PP
\fBParameters:\fP
.RS 4
\fIx1\fP First interval limit 
.br
\fIx2\fP Second interval limit 
.br
\fImaxMajSteps\fP Maximum for the number of major steps 
.br
\fImaxMinSteps\fP Maximum number of minor steps 
.br
\fIstepSize\fP Step size. If stepSize == 0, the scaleEngine calculates one.
.RE
.PP
\fBSee also:\fP
.RS 4
QwtScaleEngine::stepSize(), QwtLog10ScaleEngine::subDivide() 
.RE
.PP

.PP
Implements \fBQwtScaleEngine\fP.
.SS "\fBQwtDoubleInterval\fP QwtLog10ScaleEngine::log10 (const \fBQwtDoubleInterval\fP & interval) const\fC [protected]\fP"
.PP
Return the interval [log10(interval.minValue(), log10(interval.maxValue] 
.SS "\fBQwtDoubleInterval\fP QwtLog10ScaleEngine::pow10 (const \fBQwtDoubleInterval\fP & interval) const\fC [protected]\fP"
.PP
Return the interval [pow10(interval.minValue(), pow10(interval.maxValue] 
.SS "\fBQwtScaleTransformation\fP * QwtLog10ScaleEngine::transformation () const\fC [virtual]\fP"
.PP
Return a transformation, for logarithmic (base 10) scales 
.PP
Implements \fBQwtScaleEngine\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
