.TH "QwtPlotPanner" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPlotPanner \- \fBQwtPlotPanner\fP provides panning of a plot canvas.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_plot_panner.h>\fP
.PP
Inherits \fBQwtPanner\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPlotPanner\fP (\fBQwtPlotCanvas\fP *)"
.br
.ti -1c
.RI "virtual \fB~QwtPlotPanner\fP ()"
.br
.ti -1c
.RI "\fBQwtPlotCanvas\fP * \fBcanvas\fP ()"
.br
.ti -1c
.RI "const \fBQwtPlotCanvas\fP * \fBcanvas\fP () const "
.br
.ti -1c
.RI "\fBQwtPlot\fP * \fBplot\fP ()"
.br
.ti -1c
.RI "const \fBQwtPlot\fP * \fBplot\fP () const "
.br
.ti -1c
.RI "void \fBsetAxisEnabled\fP (int axis, bool on)"
.br
.ti -1c
.RI "bool \fBisAxisEnabled\fP (int axis) const "
.br
.in -1c
.SS "Protected Slots"

.in +1c
.ti -1c
.RI "virtual void \fBmoveCanvas\fP (int dx, int dy)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBQwtPlotPanner\fP provides panning of a plot canvas. 

\fBQwtPlotPanner\fP is a panner for a \fBQwtPlotCanvas\fP, that adjusts the scales of the axes after dropping the canvas on its new position.
.PP
Together with \fBQwtPlotZoomer\fP and \fBQwtPlotMagnifier\fP powerful ways of navigating on a \fBQwtPlot\fP widget can be implemented easily.
.PP
\fBNote:\fP
.RS 4
The axes are not updated, while dragging the canvas 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBQwtPlotZoomer\fP, \fBQwtPlotMagnifier\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtPlotPanner::QwtPlotPanner (\fBQwtPlotCanvas\fP * canvas)\fC [explicit]\fP"
.PP
Create a plot panner. 
.PP
The panner is enabled for all axes
.PP
\fBParameters:\fP
.RS 4
\fIcanvas\fP Plot canvas to pan, also the parent object
.RE
.PP
\fBSee also:\fP
.RS 4
\fBsetAxisEnabled()\fP 
.RE
.PP

.SS "QwtPlotPanner::~QwtPlotPanner ()\fC [virtual]\fP"
.PP
Destructor. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "const \fBQwtPlotCanvas\fP * QwtPlotPanner::canvas () const"
.PP
Return Observed plot canvas. 
.PP
.SS "\fBQwtPlotCanvas\fP * QwtPlotPanner::canvas ()"
.PP
Return observed plot canvas. 
.PP
.SS "bool QwtPlotPanner::isAxisEnabled (int axis) const"
.PP
Test if an axis is enabled
.PP
\fBParameters:\fP
.RS 4
\fIaxis\fP Axis, see \fBQwtPlot::Axis\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
True, if the axis is enabled
.RE
.PP
\fBSee also:\fP
.RS 4
\fBsetAxisEnabled()\fP, \fBmoveCanvas()\fP 
.RE
.PP

.SS "void QwtPlotPanner::moveCanvas (int dx, int dy)\fC [protected, virtual, slot]\fP"
.PP
Adjust the enabled axes according to dx/dy
.PP
\fBParameters:\fP
.RS 4
\fIdx\fP Pixel offset in x direction 
.br
\fIdy\fP Pixel offset in y direction
.RE
.PP
\fBSee also:\fP
.RS 4
\fBQwtPanner::panned()\fP 
.RE
.PP

.SS "const \fBQwtPlot\fP * QwtPlotPanner::plot () const"
.PP
Return plot widget, containing the observed plot canvas. 
.PP
.SS "\fBQwtPlot\fP * QwtPlotPanner::plot ()"
.PP
Return plot widget, containing the observed plot canvas. 
.PP
.SS "void QwtPlotPanner::setAxisEnabled (int axis, bool on)"
.PP
En/Disable an axis. 
.PP
Axes that are enabled will be synchronized to the result of panning. All other axes will remain unchanged.
.PP
\fBParameters:\fP
.RS 4
\fIaxis\fP Axis, see \fBQwtPlot::Axis\fP 
.br
\fIon\fP On/Off
.RE
.PP
\fBSee also:\fP
.RS 4
\fBisAxisEnabled()\fP, \fBmoveCanvas()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
