.TH "QwtPlotSvgItem" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPlotSvgItem \- A plot item, which displays data in Scalable Vector Graphics (SVG) format.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_plot_svgitem.h>\fP
.PP
Inherits \fBQwtPlotItem\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPlotSvgItem\fP (const QString &title=QString::null)"
.br
.ti -1c
.RI "\fBQwtPlotSvgItem\fP (const \fBQwtText\fP &title)"
.br
.ti -1c
.RI "virtual \fB~QwtPlotSvgItem\fP ()"
.br
.ti -1c
.RI "bool \fBloadFile\fP (const QwtDoubleRect &, const QString &fileName)"
.br
.ti -1c
.RI "bool \fBloadData\fP (const QwtDoubleRect &, const QByteArray &)"
.br
.ti -1c
.RI "virtual QwtDoubleRect \fBboundingRect\fP () const "
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *p, const \fBQwtScaleMap\fP &xMap, const \fBQwtScaleMap\fP &yMap, const QRect &rect) const "
.br
.ti -1c
.RI "virtual int \fBrtti\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBrender\fP (QPainter *painter, const QwtDoubleRect &viewBox, const QRect &rect) const "
.br
.ti -1c
.RI "QwtDoubleRect \fBviewBox\fP (const QwtDoubleRect &area) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
A plot item, which displays data in Scalable Vector Graphics (SVG) format. 

SVG images are often used to display maps 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtPlotSvgItem::QwtPlotSvgItem (const QString & title = \fCQString::null\fP)\fC [explicit]\fP"
.PP
Constructor. 
.PP
Sets the following item attributes:
.IP "\(bu" 2
QwtPlotItem::AutoScale: true
.IP "\(bu" 2
QwtPlotItem::Legend: false
.PP
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP Title 
.RE
.PP

.SS "QwtPlotSvgItem::QwtPlotSvgItem (const \fBQwtText\fP & title)\fC [explicit]\fP"
.PP
Constructor. 
.PP
Sets the following item attributes:
.IP "\(bu" 2
QwtPlotItem::AutoScale: true
.IP "\(bu" 2
QwtPlotItem::Legend: false
.PP
.PP
\fBParameters:\fP
.RS 4
\fItitle\fP Title 
.RE
.PP

.SS "QwtPlotSvgItem::~QwtPlotSvgItem ()\fC [virtual]\fP"
.PP
Destructor. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "QwtDoubleRect QwtPlotSvgItem::boundingRect () const\fC [virtual]\fP"
.PP
Bounding rect of the item. 
.PP
Reimplemented from \fBQwtPlotItem\fP.
.SS "void QwtPlotSvgItem::draw (QPainter * painter, const \fBQwtScaleMap\fP & xMap, const \fBQwtScaleMap\fP & yMap, const QRect & canvasRect) const\fC [virtual]\fP"
.PP
Draw the SVG item
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIxMap\fP X-Scale Map 
.br
\fIyMap\fP Y-Scale Map 
.br
\fIcanvasRect\fP Contents rect of the plot canvas 
.RE
.PP

.PP
Implements \fBQwtPlotItem\fP.
.SS "bool QwtPlotSvgItem::loadData (const QwtDoubleRect & rect, const QByteArray & data)"
.PP
Load SVG data
.PP
\fBParameters:\fP
.RS 4
\fIrect\fP Bounding rectangle 
.br
\fIdata\fP in SVG format
.RE
.PP
\fBReturns:\fP
.RS 4
true, if the SVG data could be loaded 
.RE
.PP

.SS "bool QwtPlotSvgItem::loadFile (const QwtDoubleRect & rect, const QString & fileName)"
.PP
Load a SVG file
.PP
\fBParameters:\fP
.RS 4
\fIrect\fP Bounding rectangle 
.br
\fIfileName\fP SVG file name
.RE
.PP
\fBReturns:\fP
.RS 4
true, if the SVG file could be loaded 
.RE
.PP

.SS "void QwtPlotSvgItem::render (QPainter * painter, const QwtDoubleRect & viewBox, const QRect & rect) const\fC [protected]\fP"
.PP
Render the SVG data
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIviewBox\fP View Box, see QSvgRenderer::viewBox 
.br
\fIrect\fP Traget rectangle on the paint device 
.RE
.PP

.SS "int QwtPlotSvgItem::rtti () const\fC [virtual]\fP"
.PP
\fBReturns:\fP
.RS 4
QwtPlotItem::Rtti_PlotSVG 
.RE
.PP

.PP
Reimplemented from \fBQwtPlotItem\fP.
.SS "QwtDoubleRect QwtPlotSvgItem::viewBox (const QwtDoubleRect & rect) const\fC [protected]\fP"
.PP
Calculate the viewBox from an rect and \fBboundingRect()\fP.
.PP
\fBParameters:\fP
.RS 4
\fIrect\fP Rectangle in scale coordinates 
.RE
.PP
\fBReturns:\fP
.RS 4
viewBox View Box, see QSvgRenderer::viewBox 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
