.TH "QwtTextEngine" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtTextEngine \- Abstract base class for rendering text strings.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_text_engine.h>\fP
.PP
Inherited by \fBQwtMathMLTextEngine\fP, \fBQwtPlainTextEngine\fP, and \fBQwtRichTextEngine\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~QwtTextEngine\fP ()"
.br
.ti -1c
.RI "virtual int \fBheightForWidth\fP (const QFont &font, int flags, const QString &text, int width) const =0"
.br
.ti -1c
.RI "virtual QSize \fBtextSize\fP (const QFont &font, int flags, const QString &text) const =0"
.br
.ti -1c
.RI "virtual bool \fBmightRender\fP (const QString &text) const =0"
.br
.ti -1c
.RI "virtual void \fBtextMargins\fP (const QFont &font, const QString &text, int &left, int &right, int &top, int &bottom) const =0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (QPainter *painter, const QRect &rect, int flags, const QString &text) const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtTextEngine\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class for rendering text strings. 

A text engine is responsible for rendering texts for a specific text format. They are used by \fBQwtText\fP to render a text.
.PP
\fBQwtPlainTextEngine\fP and \fBQwtRichTextEngine\fP are part of the Qwt library.
.PP
\fBQwtMathMLTextEngine\fP can be found in Qwt MathML extension, that needs the MathML renderer of the Qt solutions package. Unfortunately it is only available with a commercial Qt license.
.PP
\fBSee also:\fP
.RS 4
\fBQwtText::setTextEngine()\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtTextEngine::~QwtTextEngine ()\fC [virtual]\fP"
.PP
Destructor. 
.PP
.SS "QwtTextEngine::QwtTextEngine ()\fC [protected]\fP"
.PP
Constructor. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual void QwtTextEngine::draw (QPainter * painter, const QRect & rect, int flags, const QString & text) const\fC [pure virtual]\fP"
.PP
Draw the text in a clipping rectangle
.PP
\fBParameters:\fP
.RS 4
\fIpainter\fP Painter 
.br
\fIrect\fP Clipping rectangle 
.br
\fIflags\fP Bitwise OR of the flags like in for QPainter::drawText 
.br
\fItext\fP Text to be rendered 
.RE
.PP

.PP
Implemented in \fBQwtPlainTextEngine\fP, \fBQwtRichTextEngine\fP, and \fBQwtMathMLTextEngine\fP.
.SS "virtual int QwtTextEngine::heightForWidth (const QFont & font, int flags, const QString & text, int width) const\fC [pure virtual]\fP"
.PP
Find the height for a given width
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP Font of the text 
.br
\fIflags\fP Bitwise OR of the flags used like in QPainter::drawText 
.br
\fItext\fP Text to be rendered 
.br
\fIwidth\fP Width
.RE
.PP
\fBReturns:\fP
.RS 4
Calculated height 
.RE
.PP

.PP
Implemented in \fBQwtPlainTextEngine\fP, \fBQwtRichTextEngine\fP, and \fBQwtMathMLTextEngine\fP.
.SS "virtual bool QwtTextEngine::mightRender (const QString & text) const\fC [pure virtual]\fP"
.PP
Test if a string can be rendered by this text engine
.PP
\fBParameters:\fP
.RS 4
\fItext\fP Text to be tested 
.RE
.PP
\fBReturns:\fP
.RS 4
true, if it can be rendered 
.RE
.PP

.PP
Implemented in \fBQwtPlainTextEngine\fP, \fBQwtRichTextEngine\fP, and \fBQwtMathMLTextEngine\fP.
.SS "virtual void QwtTextEngine::textMargins (const QFont & font, const QString & text, int & left, int & right, int & top, int & bottom) const\fC [pure virtual]\fP"
.PP
Return margins around the texts
.PP
The textSize might include margins around the text, like QFontMetrics::descent. In situations where texts need to be aligend in detail, knowing these margins might improve the layout calculations.
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP Font of the text 
.br
\fItext\fP Text to be rendered 
.br
\fIleft\fP Return value for the left margin 
.br
\fIright\fP Return value for the right margin 
.br
\fItop\fP Return value for the top margin 
.br
\fIbottom\fP Return value for the bottom margin 
.RE
.PP

.PP
Implemented in \fBQwtPlainTextEngine\fP, \fBQwtRichTextEngine\fP, and \fBQwtMathMLTextEngine\fP.
.SS "virtual QSize QwtTextEngine::textSize (const QFont & font, int flags, const QString & text) const\fC [pure virtual]\fP"
.PP
Returns the size, that is needed to render text
.PP
\fBParameters:\fP
.RS 4
\fIfont\fP Font of the text 
.br
\fIflags\fP Bitwise OR of the flags like in for QPainter::drawText 
.br
\fItext\fP Text to be rendered
.RE
.PP
\fBReturns:\fP
.RS 4
Caluclated size 
.RE
.PP

.PP
Implemented in \fBQwtPlainTextEngine\fP, \fBQwtRichTextEngine\fP, and \fBQwtMathMLTextEngine\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
