.TH "QwtTextLabel" 3 "22 Mar 2009" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtTextLabel \- A Widget which displays a \fBQwtText\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <qwt_text_label.h>\fP
.PP
Inherited by \fBQwtLegendItem\fP.
.PP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBsetText\fP (const QString &, \fBQwtText::TextFormat\fP textFormat=QwtText::AutoText)"
.br
.ti -1c
.RI "virtual void \fBsetText\fP (const \fBQwtText\fP &)"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtTextLabel\fP (QWidget *parent=NULL)"
.br
.ti -1c
.RI "\fBQwtTextLabel\fP (const \fBQwtText\fP &, QWidget *parent=NULL)"
.br
.ti -1c
.RI "virtual \fB~QwtTextLabel\fP ()"
.br
.ti -1c
.RI "const \fBQwtText\fP & \fBtext\fP () const "
.br
.ti -1c
.RI "int \fBindent\fP () const "
.br
.ti -1c
.RI "void \fBsetIndent\fP (int)"
.br
.ti -1c
.RI "int \fBmargin\fP () const "
.br
.ti -1c
.RI "void \fBsetMargin\fP (int)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const "
.br
.ti -1c
.RI "virtual QSize \fBminimumSizeHint\fP () const "
.br
.ti -1c
.RI "virtual int \fBheightForWidth\fP (int) const "
.br
.ti -1c
.RI "QRect \fBtextRect\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *e)"
.br
.ti -1c
.RI "virtual void \fBdrawContents\fP (QPainter *)"
.br
.ti -1c
.RI "virtual void \fBdrawText\fP (QPainter *, const QRect &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Widget which displays a \fBQwtText\fP. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QwtTextLabel::QwtTextLabel (QWidget * parent = \fCNULL\fP)\fC [explicit]\fP"
.PP
Constructs an empty label. 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP Parent widget 
.RE
.PP

.SS "QwtTextLabel::QwtTextLabel (const \fBQwtText\fP & text, QWidget * parent = \fCNULL\fP)\fC [explicit]\fP"
.PP
Constructs a label that displays the text, text 
.PP
\fBParameters:\fP
.RS 4
\fIparent\fP Parent widget 
.br
\fItext\fP Text 
.RE
.PP

.SS "QwtTextLabel::~QwtTextLabel ()\fC [virtual]\fP"
.PP
Destructor. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "void QwtTextLabel::clear ()\fC [slot]\fP"
.PP
Clear the text and all \fBQwtText\fP attributes. 
.PP
.SS "void QwtTextLabel::drawContents (QPainter * painter)\fC [protected, virtual]\fP"
.PP
Redraw the text and focus indicator. 
.PP
.SS "void QwtTextLabel::drawText (QPainter * painter, const QRect & textRect)\fC [protected, virtual]\fP"
.PP
Redraw the text. 
.PP
Reimplemented in \fBQwtLegendItem\fP.
.SS "int QwtTextLabel::heightForWidth (int width) const\fC [virtual]\fP"
.PP
Returns the preferred height for this widget, given the width. 
.PP
\fBParameters:\fP
.RS 4
\fIwidth\fP Width 
.RE
.PP

.SS "int QwtTextLabel::indent () const"
.PP
Return label's text indent in pixels. 
.PP
.SS "int QwtTextLabel::margin () const"
.PP
Return label's text indent in pixels. 
.PP
.SS "QSize QwtTextLabel::minimumSizeHint () const\fC [virtual]\fP"
.PP
Return a minimum size hint. 
.PP
.SS "void QwtTextLabel::paintEvent (QPaintEvent * event)\fC [protected, virtual]\fP"
.PP
Qt paint event 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP Paint event 
.RE
.PP

.PP
Reimplemented in \fBQwtLegendItem\fP.
.SS "void QwtTextLabel::setIndent (int indent)"
.PP
Set label's text indent in pixels 
.PP
\fBParameters:\fP
.RS 4
\fIindent\fP Indentation in pixels 
.RE
.PP

.SS "void QwtTextLabel::setMargin (int margin)"
.PP
Set label's margin in pixels 
.PP
\fBParameters:\fP
.RS 4
\fImargin\fP Margin in pixels 
.RE
.PP

.SS "void QwtTextLabel::setText (const \fBQwtText\fP & text)\fC [virtual, slot]\fP"
.PP
Change the label's text 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP New text 
.RE
.PP

.PP
Reimplemented in \fBQwtLegendItem\fP.
.SS "void QwtTextLabel::setText (const QString & text, \fBQwtText::TextFormat\fP textFormat = \fCQwtText::AutoText\fP)\fC [slot]\fP"
.PP
Change the label's text, keeping all other \fBQwtText\fP attributes 
.PP
\fBParameters:\fP
.RS 4
\fItext\fP New text 
.br
\fItextFormat\fP Format of text
.RE
.PP
\fBSee also:\fP
.RS 4
\fBQwtText\fP 
.RE
.PP

.SS "QSize QwtTextLabel::sizeHint () const\fC [virtual]\fP"
.PP
Return label's margin in pixels. 
.PP
Reimplemented in \fBQwtLegendItem\fP.
.SS "const \fBQwtText\fP & QwtTextLabel::text () const"
.PP
Return the text. 
.PP
.SS "QRect QwtTextLabel::textRect () const"
.PP
Calculate the rect for the text in widget coordinates 
.PP
\fBReturns:\fP
.RS 4
Text rect 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code.
