env:
  global:
  - CONAN_USERNAME: fbergmann
  - CONAN_LOGIN_USERNAME: fbergmann
  - CONAN_CHANNEL: testing
  - CONAN_UPLOAD: https://api.bintray.com/conan/fbergmann/conan
  - CONAN_STABLE_BRANCH_PATTERN: release/*
  - CONAN_BUILD_POLICY: missing
  - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  - CONAN_DOCKER_32_IMAGES: 1
  - CONAN_UPLOAD_DEPENDENCIES: "all"
addons:
  sonarcloud:
    organization: "fbergmann"
    token:
      secure: eFSqsDOcM1uDc9DOwPb2oMUgDEWvS+R0DkIGPHxLVpUvy7ovWuyq+1+5+zwcg7+Pgpwry/94xW7QyhYdPq8SG2Py0IoK2cg+6RNd9jmoQHMgmK1SxrpboULjr//qoe1JtEiPGkETTTcrHAlMjCsxMI+r725DTIWBWZSyJc0dl62sk8lpECLDgPJQ7MKTO7aeqDPGWWUFazKGgEOf1qur7jNjs3vvwhikYVWIX7If/H+0itPmRI95ipBvussJ3BGmqiZ49PIymqCh5GT2qAMp0xdl+rez9cGTUjKmckEo4XvBkCL1WY/Bhy8uCgTmgLWVh3IhZy2DuH3z8QkVqSMMZUAsuWXyTqIxu+OBpL6UiZEa8JGEUyI2+w96keDISotDrNryN4QXaVJu2KlomUjQi5e4nCnEBrcs3XinlSdk6gu7KA7/HUGUPx540pJ1kcvJcgS44MGA68sqOzKrdYu3/7oRCKyrskiafPh3+fKej69RYxIjS0MbG3m8NM1bvBo/+eZyTV53lmOkaw/XDvEvaeZg8Dziep8GjRV08jbsrp9ZDXEfpk1uQG34/v87d6pfgJjbuk5zdLtFvN6AACzPGLzpqBxa6GEHK0Jyfi2Gk+YnnVfrN2FvitAyVnZdRpTEmR4+X/pM2YHPVVTvjkxKaIokil2Qomxj+Kw0KWkwJZo=
linux:
  os: linux
  dist: xenial
  language: python
  python: '3.7'
  services: &1
  - docker
osx:
  os: osx
  language: generic
matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: '3.7'
    services: *1
    env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9
install:
- chmod +x .ci/install.sh
- "./.ci/install.sh"
script:
- chmod +x .ci/run.sh
- "./.ci/run.sh"
