name: manylinux

on: 
  push:
    paths:
        - "**"
        - "!.github/**"
        - ".github/workflows/manylinux.yml"

defaults:
  run:
    shell: bash

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: manylinux
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
     - uses: actions/checkout@v2
    
     - name: intall latest cmake
       run: | 
            /opt/python/cp38-cp38/bin/pip install cmake
            ln -s /opt/python/cp38-cp38/bin/cmake /usr/bin/cmake

     - name: Configure CMake
       run: cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UI_DEPS=OFF -DCMAKE_INSTALL_PREFIX=./install/

     - name: Build
       working-directory: build
       run: cmake --build . --config $BUILD_TYPE -j `nproc`

     - name: binary archive
       uses: actions/upload-artifact@v2
       with:
        name: manyliunux
        path: install/*
        retention-days: 90
        if-no-files-found: error
