name: manylinux

on: 
  workflow_dispatch:  
  push:
    paths:
        - "**"
        - "!.github/**"
        - ".github/workflows/manylinux.yml"

defaults:
  run:
    shell: bash

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: manylinux
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_28_x86_64
    steps:
     - uses: actions/checkout@v2
    
     - name: install latest cmake
       run: | 
            /opt/python/cp38-cp38/bin/pip install cmake
            ln -s /opt/python/cp38-cp38/bin/cmake /usr/bin/cmake

     - name: Configure CMake
       run: |
            git config --global --add safe.directory $PWD
            pushd src/libuuid-1.0.3/
            aclocal && libtoolize --force && automake --add-missing && autoreconf --force --install
            popd
            cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_UI_DEPS=OFF -DBUILD_uuid=ON -DCMAKE_INSTALL_PREFIX=./install/

     - name: Build
       working-directory: build
       run: |
         cmake --build . --config $BUILD_TYPE -t Libuuid
         cmake --build . --config $BUILD_TYPE -j `nproc`

     - name: Patch cmake files
       run: |
            sed -i 's|'$PWD'/install/|${_IMPORT_PREFIX}/|g'  $PWD/install/lib64/cmake/*.cmake

     - name: binary archive
       uses: actions/upload-artifact@v4
       with:
        name: manylinux_2_28_x86_64
        path: install/*
        retention-days: 90
        if-no-files-found: error
